name: Deploy app React

on:
  push:
    branches:
      - main

jobs:
  build:
    name: Build App
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
      
      - name: Set Up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20'

      - name: Set env vars
        run: |
          echo "${{ secrets.ENV }}" > .env

      - name: Install Dependencies
        run: npm install
        
      - name: Build
        run: npm run build

      - name: Pack
        run: |
          tar -czvf educai.tar.gz build/
          ls -lha
      
      - name: Deploy
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 400 ~/.ssh/id_rsa
          echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config
          scp educai.tar.gz infra@${{ vars.SERVER_ADDRESS }}:/home/infra/
          ssh infra@${{ vars.SERVER_ADDRESS }} "rm -rf /var/www/educai/build && tar -xzvf /home/infra/educai.tar.gz -C /var/www/educai/"


  # deploy:
  #   name: Deploy app
  #   runs-on: ubuntu-latest
  #   needs: build

  #   steps:
